## DGP ##
# Number of arms (including control)
K: 40
# Number of covariates
#p: 80
p: 76
# Gaussian noise to rewards
noise_std: 1
# Control INDEX
ctr: 0
## DESIGN ##
# Experiment length
T: 4000
# Number of initial draws (initial batch size)
num_init_draws: T//5
# Final batch
final_batch_list: T//5
# Number of batches between first and final batch
num_batches: 3
# probability floor
floor: 0.2
## EVALUATION ##
# Polynomial decay parameter [0, 1];
# zero means no decay (uniform weights).
polydecay_rate: 0
## SHERLOCK CONFIG ##
num_threads: 1